const OK_STATUS_CODE = 200;
const CREATED_STATUS_CODE = 201;
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_ACCESS_STATUS_CODE = 401;
const NOT_FOUND_STATUS_CODE = 404;
const UNABLE_TO_PROCESS_STATUS_CODE = 422;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

export {
  BAD_REQUEST_STATUS_CODE,
  OK_STATUS_CODE,
  CREATED_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  UNABLE_TO_PROCESS_STATUS_CODE,
  UNAUTHORIZED_ACCESS_STATUS_CODE,
};
